#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division, print_function

import os
import glob
import argparse
import numpy as np
import pandas as pd


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    # Required arguments.
    parser.add_argument("pattern", help="the directory pattern")
    parser.add_argument("results", help="the results location")
    args = parser.parse_args()

    # Loop over the matching directories.
    fns = glob.glob(args.pattern)
    features = None
    for ind, feat_fn in enumerate(fns):
        if (ind + 1) % 500 == 0:
            print(100 * (ind + 1) / len(fns))

        try:
            df = pd.read_hdf(feat_fn, "features")
        except KeyError:
            continue
        df["meta_filename"] = feat_fn
        if features is None:
            features = df
        else:
            features = features.append(df, ignore_index=True)

    features.to_hdf(os.path.abspath(args.results), "features", mode="w")
