#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division, print_function

import os
import json
from ketu.k2.basis import build


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="build the ELC basis")
    parser.add_argument("spec", help="the JSON campaign spec")
    args = parser.parse_args()
    spec = json.load(open(args.spec, "r"))
    bp = os.path.join(spec["data_root"])
    lcs = os.path.join(bp, "lightcurves/c{0:.0f}/*/*/ktwo*.fits"
                       .format(spec["campaign"]))
    outfile = os.path.join(bp, spec["basis_file"])
    build(lcs, outfile)
