#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import division, print_function
from ketu.k2.basis import build


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(
        description="Build the basis."
    )
    parser.add_argument("lcs",
                        help=("pattern for the LC files. For example: "
                              "'lightcurves/c1/*/*/*.fits'"))
    parser.add_argument("outfile",
                        help="path where the basis should be saved")
    args = parser.parse_args()
    build(args.lcs, args.outfile)
